[package]
edition = "2021"
name = "migration"
publish = false
version = "0.1.0"

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
db = {path = "../db"}
#
anyhow = "1.0.55"
sea-schema = {version = "0.7.1", default-features = false, features = ["migration"]}
# "debug-print"
